const nodemailer = require("nodemailer");
const Mailgen = require("mailgen");

const config = require("../config/config");

const transporter = nodemailer.createTransport({
  service: "gmail",
  port: 465,
  secure: true,
  auth: {
    user: config.EMAIL,
    pass: config.EMAIL_PASSKEY,
  },
});

// Initialize nodemailer transporter
// const transporter = nodemailer.createTransport({
//   host: config.EMAIL_SERVICE, // host for mailtrap
//   port: config.EMAIL_PORT,
//   // secure: true,
//   auth: {
//     user: config.EMAIL_USERNAME,
//     pass: config.EMAIL_PASSWORD,
//   },
// });

// For more info on how mailgen content work visit https://github.com/eladnava/mailgen#readme
// Generate the plaintext version of the e-mail (for clients that do not support HTML)

// Initialize Mailgen instance for generating email templates
const mailGenerator = new Mailgen({
  theme: "default",
  product: {
    name: "Sole Mound",
    link: "https://github.com/muhammadranju/sole-mound-api",
  },
});

/**
 * Send email using nodemailer transporter
 * @param {Object} options - Options for sending email
 * @param {string} options.email - Recipient email address
 * @param {string} options.subject - Email subject
 * @param {Mailgen.Content} options.mailgenContent - Email content generated by Mailgen
 */
async function sendEmail(options) {
  const emailHtml = mailGenerator.generate(options.mailgenContent);
  const emailTextual = mailGenerator.generatePlaintext(options.mailgenContent);

  // Send email with defined transport object
  const info = await transporter.sendMail({
    from: `"Sole Mound 👻"${config.USER_EMAIL}`, // sender address
    // from: `"Google"<mail.noreply@gmail.com>`, // sender address
    to: options.email, // Recipient(s) address
    subject: options.subject, /// Email subject
    text: emailTextual, // Plain text body
    html: emailHtml, // HTML body
  });

  console.log("Message successfully sent at: %s", info.messageId);
}

/**
 * Generate Mailgen content for email verification
 * @param {string} username - Username of the recipient
 * @param {string} verificationUrl - Verification URL for email verification
 * @returns {Mailgen.Content} - Mailgen content for email verification
 */
const emailVerificationMailgenContent = (username, verificationUrl) => {
  return {
    body: {
      name: username,
      intro: "Welcome to our app! We're very excited to have you on board.",
      action: {
        instructions:
          "To verify your email please click on the following button:",
        button: {
          color: "#22c55e", // Action button color
          text: "Conform your account →",
          link: verificationUrl, // Verification URL
        },
      },
      outro:
        "Need help, or have questions? Just reply to this email, we'd love to help.",
    },
  };
};

/**
 * Generate Mailgen content for forgot password email
 * @param {string} username - Username of the recipient
 * @param {string} OTP - OTP for forgot password process
 * @returns {Mailgen.Content} - Mailgen content for forgot password email
 */
const forgotPasswordMailgenContent = (username, OTP) => {
  return {
    body: {
      name: username,
      intro: "We received a request to reset the password of your account",
      action: {
        instructions:
          "To reset your password, enter the following OTP in the password reset form:",
        button: {
          //   color: "#e11d48", // Action button color
          text: "Your OTP is " + `<h1><strong>${OTP}</strong></h1>`,

          //   link: OTP, // Password reset URL
        },
      },
      outro:
        "Need help, or have questions? Just reply to this email, we'd love to help.",
    },
  };
};
const emailOTPVerificationMailgenContent = (username, OTP) => {
  return {
    body: {
      name: username,
      intro: "We received a request to for your email verification",
      action: {
        instructions:
          "To verify your email, enter the following OTP in the verification form:",
        button: {
          //   color: "#e11d48", // Action button color
          text: "Your OTP is " + `<h1><strong>${OTP}</strong></h1>`,

          //   link: OTP, // Password reset URL
        },
      },
      outro:
        "Need help, or have questions? Just reply to this email, we'd love to help.",
    },
  };
};

module.exports = {
  sendEmail,
  emailVerificationMailgenContent,
  forgotPasswordMailgenContent,
  emailOTPVerificationMailgenContent,
};
