/* eslint-disable no-undef */
const _config = {
  BASE_URL: process.env.BASE_URL,
  PORT: process.env.PORT,
  MONGODB_URI: process.env.MONGODB_URI,
  MONGODB_URI_LOCAL: process.env.MONGODB_URI_LOCAL,

  FRONTEND_URL: process.env.FRONTEND_URL,

  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY: process.env.ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY,

  SELLER_ACCESS_TOKEN_SECRET: process.env.SELLER_ACCESS_TOKEN_SECRET,
  SELLER_ACCESS_TOKEN_EXPIRY: process.env.SELLER_ACCESS_TOKEN_EXPIRY,
  SELLER_REFRESH_TOKEN_SECRET: process.env.SELLER_REFRESH_TOKEN_SECRET,
  SELLER_REFRESH_TOKEN_EXPIRY: process.env.SELLER_REFRESH_TOKEN_EXPIRY,

  ADMIN_ACCESS_TOKEN_SECRET: process.env.ADMIN_ACCESS_TOKEN_SECRET,
  ADMIN_ACCESS_TOKEN_EXPIRY: process.env.ADMIN_ACCESS_TOKEN_EXPIRY,
  ADMIN_REFRESH_TOKEN_SECRET: process.env.ADMIN_REFRESH_TOKEN_SECRET,
  ADMIN_REFRESH_TOKEN_EXPIRY: process.env.ADMIN_REFRESH_TOKEN_EXPIRY,

  SELLER_COOKIE_SECRET_KEY: process.env.SELLER_COOKIE_SECRET_KEY,
  COOKIE_SECRET_KEY: process.env.COOKIE_SECRET_KEY,
  SESSION_SECRET: process.env.SESSION_SECRET,

  EMAIL: process.env.EMAIL,
  EMAIL_PASSKEY: process.env.EMAIL_PASSKEY,

  EMAIL_SERVICE: process.env.EMAIL_SERVICE,
  EMAIL_PORT: process.env.EMAIL_PORT,
  EMAIL_USERNAME: process.env.EMAIL_USERNAME,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  //   SSL_STORE_ID: process.env.SSL_STORE_ID,
  //   SSL_STORE_PASSWORD: process.env.SSL_STORE_PASSWORD,
  //   SSL_STORE_IS_LIVE: process.env.SSL_STORE_IS_LIVE,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,

  FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
  FACEBOOK_CALLBACK_URL: process.env.FACEBOOK_CALLBACK_URL,

  APPLE_SERVICE_ID: process.env.APPLE_SERVICE_ID,
  APPLE_TEAM_ID: process.env.APPLE_TEAM_ID,
  APPLE_KEY_ID: process.env.APPLE_KEY_ID,
  APPLE_PRIVATE_KEY_PATH: process.env.APPLE_PRIVATE_KEY_PATH,
  APPLE_CALLBACK_URL: process.env.APPLE_CALLBACK_URL,

  ENV: process.env.NODE_ENV,
  USER_EMAIL: process.env.EMAIL,
  REDIS_USERNAME: process.env.REDIS_USERNAME,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
};

const config = Object.freeze(_config);

module.exports = config;
